### ISSUE TITLE
Gor an out of range error.

### ISSUE THREAD

**Issue by kdschlosser** [consp/apim-asbuilt-decode#6] opened 2022-02-03 20:47 UTC
```
[20, 35, 50, 55, 70, 76, 92, 102, 127, 152]
Device is Sync 3
Loaded 9 blocks, 122 bytes
out of range {'name': 'ADAS Feature Level', 'index': 142, 'byte': 5, 'bit': 0, 'size': 8, 'type': 'table', 'table': '_AFL'}
out of range {'name': 'Parking Assistance', 'index': 143, 'byte': 6, 'bit': 0, 'size': 8, 'type': 'table', 'table': '__PA'}
```

and here is the asbuilt data
the asbuilt data came from ford etis

[1FM5K8GC1NGA14823.zip](https://github.com/consp/apim-asbuilt-decode/files/7998103/1FM5K8GC1NGA14823.zip)

**Comment by consp** [comment] 2022-02-04 08:54
Thank you for the info, I'll take a look at it this weekend. Which version of Sync 3 do you have (specifically the build number). It looks like Ford introduced some new ADAS options not yet present in the application.

You can find the build version on the device under settings -> general settings -> about sync and it will say "Software version [number]" and "Build [number]_PRODUCT", the numbers I'm interested in.

**Comment by kdschlosser** [comment] 2022-02-04 15:01
Not my vehicle. I would assume it is the latest version of sync3 as the vehicle is a 2022 Ford Explorer ST.

There is something else you can add to the program. I noticed you only target the APIM (7D0). There is the ACM (Audio Control Module) which starts with 727 that has some really useful things that could be adjusted. One of them is the Software Engine Sound Enhancement which has to be the lamest thing I have ever seen a vehicle manufacturer do.

If memory serves it should be the 10th bit (msb) of the first code.

**Comment by consp** [comment] 2022-02-04 15:20
> Not my vehicle. I would assume it is the latest version of sync3 as the vehicle is a 2022 Ford Explorer ST.

Probably 3.4 with 20xxx build, I guess the problem is the newer versions have different settings for the camera's. Should be easily fixed.

> There is something else you can add to the program. I noticed you only target the APIM (7D0). There is the ACM (Audio Control Module) which starts with 727 that has some really useful things that could be adjusted. One of them is the Software Engine Sound Enhancement which has to be the lamest thing I have ever seen a vehicle manufacturer do.
> 
> If memory serves it should be the 10th bit (msb) of the first code.

There is a -very- wide variety of modules in the modules responding to 727 with all kinds of settings which is quite hard to identify which one it is just from the asbuilt data. From instance some of the European ones only have one settings byte which does mostly nothing to the US versions which have a lot like yours does. It also depends on the settings in the central configuration and vehicle type what the bytes do which is probably something most users will not look into. For example radios from EU Focuses will work in Fiesta's but it changes the settings in the 727 asbuilt data completely after installation and you cannot tell the difference by looking at the calibration data as it is updated on the fly as far as I know (I'm no expert here, just what my car shows). I also do not have any detailed information about the actual settings, and it's less easier to find out since there is no debug info in the firmware. It's probably best to stick to the info provided by the vehicle specific forums for now.

**Comment by kdschlosser** [comment] 2022-02-04 21:28
That's where I got the information about that bit turning off that engine sound feature. The problem with the forums are they are ding dongs and telling everyone to change 1xFF to 19FF where x is whatever your vehicle has for a current hex number.

So when breaking down the 16 bit hex code into bits I found that changing what was a 4 in my case to a 9 turned off one bit and turned on 2 others. I can't imagine that Ford would have 3 bits for a simple on/off of a feature.

**Comment by consp** [comment] 2022-02-04 23:28
I can understand the issues with the "language" involved. It's not always clear what to do or what to change. My problem is I have no way to check or verify what works so I'm mostly stuck with what I can test on other peoples vehicles or my own and or trust other sources. And considering the ACM changes they are lacking consistency.

Looking at the home usage it would be nice to include if you have some form of information which I can use relating to the settings in the ACM I maybe can include them. 

But as far as I know there is no legal way for me to get that info first hand ... (I will not go into details too much but providing info about that means decrypting the Ford IDS stuff which, while easy for those familiar with any form of proper encryption, is most likely illegal in most places which is outside my prerogative to disclose).

**Comment by consp** [comment] 2022-02-05 12:55
It has been fixed in the new release. A wrong variable was loaded which works ... mostly (Sync 4 field lengths instead of Sync 3)

See: https://github.com/consp/apim-asbuilt-decode/releases/tag/1.3c

**Closed as completed by consp** 2022-02-05 12:55 UTC
